server:
  port: 8083

kc:
  base-url: http://localhost:8180/auth
  realm: synerzip-ad
  realm-url: ${kc.base-url}/realms/${kc.realm}

spring:
  security:
    oauth2:
      client:
        registration:
          synerzip-ad:
            client-id: sample-service
            client-name: sample-service
            client-secret: 55bd8440-fd1b-4307-a6af-85e620c55aeb
            provider: keycloak
            authorization-grant-type: authorization_code
            scope: openid, profile
            redirect-uri-template: "http://localhost:8000/oauth2/callback"
        provider:
          keycloak:
            authorization-uri: ${kc.realm-url}/protocol/openid-connect/auth
            jwk-set-uri: ${kc.realm-url}/protocol/openid-connect/certs
            token-uri: ${kc.realm-url}/protocol/openid-connect/token
# would be cool if there was a end-session-uri to propagate logouts

#  User info endpoint not needed since Keycloak uses self-contained value tokens
#            user-info-uri: ${kc.realm-url}/protocol/openid-connect/userinfo
            user-name-attribute: preferred_username
